### ISSUE TITLE
Add support for the Proton Saga

### ISSUE THREAD

**Issue by Mohdhafez86** [ElectricSidecar/meta#2]
Please [check for an existing repository](https://github.com/orgs/ElectricSidecar/repositories) before filing new issues.

**Comment by electricsidecar-dev** [comment]
Hello, which vehicle make/model were you wanting support for?

**Comment by electricsidecar-dev** [comment]
Based on https://github.com/ElectricSidecar/meta/issues/3 it looks like you're trying to request support for the Proton Saga?

**Comment by electricsidecar-dev** [comment]
Please visit http://sidecar.clutch.engineering/beta/ and follow the steps there to register your vehicle to test with Sidecar.
